### ISSUE TITLE
[Feature request] 增加BJ支持、增加多文件夹支持

### ISSUE THREAD

**Issue by mizhewei** [Number178/kikoeru-express#1]
1.增加BJ支持
BJ（商抓）是和RJ（同人作品）类似的在Dlsite上线的音声作品，元数据抓取没有任何差别，仅需要支持BJ+数字的文件夹匹配，例子https://www.dlsite.com/girls-drama/work/=/product_id/BJ201302.html/

2.增加多文件夹支持
本地存储的音声文件夹有多个，有的存放了抓的本体，有的是特典、赠品等，文件夹名都含有相同的RJ、BJ号；尤其是在BJ的作品中。希望构建数据库扫文件夹时能一起加入

**Comment by mizhewei** [comment]
看了下Docker新版本，扫库的时候BJ的没有扫描进去，本地文件夹名例子：BJ172327 黒い夢 第三夜 ♯34 salon[錦戸智久  刺草ネトル)[181130]
另外，网页：http://192.168.31.2:8888/work/1128258，这里的编号只有数字，不知道会不会冲突；封面图左上角显示编号不知道会不会有问题

**Comment by Number178** [comment]
BJ在独立的分支中已支持，试用可以拉取dockerhub里 number17/kikoeru:bj 这个tag的镜像，里面也一并增加了VJ的支持，我这些作品听的不多，你可以用着试试，有bug的欢迎反馈

**Comment by Number178** [comment]
BJ支持已更新到docker hub latest，多文件夹暂无计划支持
