### ISSUE TITLE
[Feature request] 补充搜索API

### ISSUE THREAD

**Issue by mizhewei** [Number178/kikoeru-express#10]
补充搜索API，要想要配合油猴脚本，DLsitejump来检查自己的kikoeru库里是否已经存在此作品。
目前的前端搜索页面是一个使用JavaScript动态生成内容的单页应用程序（SPA）。而由于GM_xmlhttpRequest（或者标准的fetch）只能获取原始的HTML响应，它们无法执行或等待JavaScript动态生成的内容。
希望支持搜索API
感谢

**Comment by Number178** [comment]
就是搜索番号，判断数据库里有没有这个作品吗？现有api就已经可以支持搜索了，比如下面这
```
http://127.0.0.1:8080/api/search?page=1&sort=desc&order=created_at&nsfw=0&lyric=&seed=50&isAdvance=0&keyword=RJ128949
```

响应
```
{
    "works": [
        {
            "id": 128949,
            "created_at": "2024-03-06 15:02:14",
            "updated_at": "2024-03-06 15:02:14",
            ...
        }
    ],
    "pagination": {
        "currentPage": 1,
        "pageSize": 12,
        "totalCount": 1
    }
}
```
你自己判断返回的数量是不是大于1就行

**Comment by mizhewei** [comment]
好的大佬。还有一个问题，如果设置了用户验证，这个API应该怎么写

**Comment by Number178** [comment]
给query加token就可以，比如url变成 `http://127.0...keyword=RJ128949&token=rekjfekwjeruifjewojfe`。

具体token是多少，一种方法是发送登陆请求获取，比如可以参考这里的python代码[kikoeru-translate:loginKikoeru函数](https://github.com/Number178/kikoeru-translate/blob/9d74dd39def8c6eedfa6fa7612197db3c1e2bad9/server/kikoeru_worker.py#L51)。

第二种方法，是去已经登陆的kikoeru网页调控制台，取localStorage的token内容，就是jwt-token为key的值，注意把value前的`__q_strn|` 给去掉，只留后面的字符串作token。
