### ISSUE TITLE
[Bug] 下载封面图片过程中出错

### ISSUE THREAD

**Issue by Joyist2021** [Number178/kikoeru-express#11]
**问题描述**
下载封面图片过程中出错

**错误信息**

ID_TYPE_LIST =  [ 'RJ', 'BJ', 'VJ' ]
ID_TYPE_TO_NUMBER =  { RJ: 0, BJ: 1, VJ: 2 }
Express server started on port 8888 at 0.0.0.0
ID_TYPE_LIST =  [ 'RJ', 'BJ', 'VJ' ]
ID_TYPE_TO_NUMBER =  { RJ: 0, BJ: 1, VJ: 2 }
 * 数据库结构已经存在.
main log 清理本地不再存在的音声的数据与封面图片...
main log 清理完成. 现在开始扫描...
normalize  RJ01153746  to  RJ01153746
main log 共找到 1 个音声文件夹.
LOG.task.add 'RJ01153746'
task[RJ01153746] log 封面图片缺失，重新下载封面图片...
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 1 次重试请求
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 2 次重试请求
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 3 次重试请求
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 4 次重试请求
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 5 次重试请求
task[RJ01153746] log 在获取真实的封面id（适配那些翻译作品的封面问题） 过程中出错: Cannot read properties of undefined (reading 'status')
task[RJ01153746] log 从 DLsite 下载封面...
task[RJ01153746] log 在下载封面 RJ01153746_img_sam.jpg 过程中出错: Request failed with status code 404, url = https://img.dlsite.jp/modpub/images2/work/doujin/RJ01154000/RJ01153746_img_sam.jpg
main log [RJ01153746] 在下载封面 RJ01153746_img_sam.jpg 过程中出错: Request failed with status code 404, url = https://img.dlsite.jp/modpub/images2/work/doujin/RJ01154000/RJ01153746_img_sam.jpg
task[RJ01153746] log 在下载封面 RJ01153746_img_main.jpg 过程中出错: Request failed with status code 404, url = https://img.dlsite.jp/modpub/images2/work/doujin/RJ01154000/RJ01153746_img_main.jpg
main log [RJ01153746] 在下载封面 RJ01153746_img_main.jpg 过程中出错: Request failed with status code 404, url = https://img.dlsite.jp/modpub/images2/work/doujin/RJ01154000/RJ01153746_img_main.jpg
task[RJ01153746] log 在下载封面 RJ01153746_img_240x240.jpg 过程中出错: Request failed with status code 404, url = https://img.dlsite.jp/resize/images2/work/doujin/RJ01154000/RJ01153746_img_main_240x240.jpg
main log [RJ01153746] 在下载封面 RJ01153746_img_240x240.jpg 过程中出错: Request failed with status code 404, url = https://img.dlsite.jp/resize/images2/work/doujin/RJ01154000/RJ01153746_img_main_240x240.jpg
main log RJ01153746 作品本身在DlSite上缺失部分图片，忽略这些问题
LOG.task.remove 'RJ01153746'
 * 扫描完成: 新增 0 个，跳过 1 个，失败 0 个.

**版本**

 - 系统：docker pull number17/kikoeru:latest
 - 安装方式：Docker安装
 - 浏览器：Chrome/Firefox/Safari
 - 程序版本：v0.6.7-20240329

**截图**

**实际可访问的图片地址**

https://img.dlsite.jp/modpub/images2/work/doujin/RJ01109000/RJ01108347_img_main.jpg
https://img.dlsite.jp/modpub/images2/work/doujin/RJ01154000/RJ01153746_img_smp1.jpg
https://img.dlsite.jp/modpub/images2/work/doujin/RJ01154000/RJ01153746_img_smp2.jpg
https://img.dlsite.jp/modpub/images2/work/doujin/RJ01154000/RJ01153746_img_smp3.jpg

**Comment by Number178** [comment]
报错日志里请求html网页请求了5次，然后失败了：
```
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 1 次重试请求
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 2 次重试请求
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 3 次重试请求
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 4 次重试请求
https://www.dlsite.com/maniax/work/=/product_id/RJ01153746.html 第 5 次重试请求
```
所以看起来是网络问题导致了图片下载失败，至于报错信息没有反应出来网络问题，这就是另一回事了，后面会优化这块错误信息显示。但是根本上要解决封面下载失败的问题，你得检查一下docker宿主机的网络环境，确保能够连接dlsite。这边本地测试`RJ01153746`是能够正常抓取到封面的。
