### ISSUE TITLE
[Feature request] 多语言版

### ISSUE THREAD

**Issue by mizhewei** [Number178/kikoeru-express#12]
如题，大家一起来翻译后的抓有多个语言版本
数据库抓取时能否抓取标记
使用搜索或者API搜索能否实现搜某一语言版本关联其他版本（简中优先)
work页面可否关联跳转

好像要修改的很多，不支持也没关系，只是愿望设想。感谢您持续的更新和维护🙏

**Comment by Number178** [comment]
多语言关联版本已支持，左边栏“聚合搜索”页或者作品详情页可以显示同一作品的多个语言版本，没有优先级排序，旧式搜索页暂不支持这个功能。
