### ISSUE TITLE
[Feature request] 播放器进度条能难用，只支持拖动，不支持点击跳转

### ISSUE THREAD

**Issue by sqsq37** [Number178/kikoeru-express#13]
理解作者是想防误触了，但是弊大于利了
希望和asmr.one点击跳转进度

或者和类emby库一样可以直接调用外部播放器吗，可以的话就一切迎刃而解了

**Comment by Number178** [comment]
是指网页还是iOS客户端上的进度条啊

**Comment by sqsq37** [comment]
> 是指网页还是iOS客户端上的进度条啊

网页端

**Comment by Number178** [comment]
网页端的播放器进度条支持跳转啊，你说的是右下角那个有封面、音量条的播放器组件吧。

**Comment by sqsq37** [comment]
> 右下角那个有封面、音量条的播放器组件吧。

对就是那个

**Comment by Number178** [comment]
那奇怪了，这边电脑、手机上都可以点击跳转，你要不换其他设备试试看？

**Comment by Number178** [comment]
网页版中，播放器支持点击跳转到进度条任意位置，本地无法复现这里提到的问题，这个issue先close了
