### ISSUE TITLE
[Bug] 设置服务器后主页没有显示作品

### ISSUE THREAD

**Issue by chingyuanli** [Number178/kikoeru-express#17]
**问题描述**
服务器设置成功，登录也成功，但是不管怎么刷新就是一个作品都显示不出来

**版本**

 - 系统：iOS 17.3.1
 - 安装方式：Testflight
 - 程序版本：1.1 (34)

**截图**
![unnamed (1)](https://github.com/Number178/kikoeru-express/assets/72701637/30d21d96-20cd-4a84-94c5-5a2085407e48)
![unnamed](https://github.com/Number178/kikoeru-express/assets/72701637/d6120f44-f414-46c5-a876-0168263775c8)

**Comment by Number178** [comment]
这个客户端暂时仅支持自行部署的kikoeru服务器，具体可以参考这里的说明[Kikoeru iOS 客户端](https://number17.online/docs/kikoeru-app)。
![note](https://github.com/Number178/kikoeru-express/assets/154647667/760b4017-a398-46eb-a00b-ce22c71821e3)
