### ISSUE TITLE
[Feature request] 入库的作品标题支持随作品语言自动调整爬取用语言

### ISSUE THREAD

**Issue by TIMEpings** [Number178/kikoeru-express#19]
以“大家一起来翻译”的简体中文与繁体中文制品为例。如果界面语言为简体中文，对于简体中文的大家翻作品可以爬取到简中译者翻译过的标题，但繁体中文的作品由于没有设置简中的标题，在简中环境下的标题就会得到“【繁体中文版】+日文标题”。同理，如果以繁体中文作为界面语言就得到繁中译者翻译的标题，但简中作品的标题就变成“【簡体中文版】+日文标题”了。这个特性在DLsite网页端切换界面语言可以很直观的反映出来。

我的Kikoeru入库时默认用简中语言爬取，举个例子，RJ01148017这个大家翻繁体中文作品入库后是这样显示的：
![屏幕截图_25-5-2024_35537_192 168 0 105](https://github.com/Number178/kikoeru-express/assets/90127218/b46f7607-22d8-4691-97be-6ece12a616af)
因为DLsite界面语言为简体中文时，由于没有对应的简中标题翻译，标题就会默认日文：
![屏幕截图_25-5-2024_4055_www dlsite com](https://github.com/Number178/kikoeru-express/assets/90127218/000b4b94-993d-4e95-a7bc-7d0743bf640b)
但把界面语言改成繁体中文，就可以得到繁中翻译的标题了：
![屏幕截图_25-5-2024_35636_www dlsite com](https://github.com/Number178/kikoeru-express/assets/90127218/59dff89a-3f3f-404f-9bc5-3b37d991971c)

所以，请问是否有实现的可能，让Kikoeru在爬取标题的时候先判断作品支持的语言，如果是简中就爬取简中环境下的标题，如果是繁中就爬取繁中环境下的标题；如果该作品支持多个语言或是仅支持日语，就可以让用户自定义一个缺省语言爬取（或者默认以简体中文环境爬取），对于有些日文作品（如RJ299717）也存在翻译好的中文语言标题。这样的话，Kikoeru音声库里就可以尽可能的以中文标题显示。

**Comment by Number178** [comment]
已合入 @averageFOSSenjoyer 提供的代码修复，release已发布
