### ISSUE TITLE
[Bug] 请问作品内的目录结构是设计好的展示所有包含媒体文件的文件夹吗？

### ISSUE THREAD

**Issue by yoyokirby** [Number178/kikoeru-express#21]
**问题描述**
当前的情况：展示每个包含了媒体文件的文件夹
![image](https://github.com/Number178/kikoeru-express/assets/13408770/868e158e-bb06-41eb-9f82-955ec5642182)
期望的情况：按照实际目录展示。先显示1.音声 2.イラスト，点开1.音声再展示4个文件夹。

请问确实是写成这样的吗？有时有些选择支式的作品，会嵌套多层文件夹，这样子会把所有的标题都显示出来，产生剧透。

**Comment by Number178** [comment]
看着是文件夹路径划分的bug，以前的代码估计只考虑了windows平台，全部都是用 \ 划分文件夹路径，导致文件夹层级粘到一起了，已增加 / 划分，可用最新release版本试一下

**Comment by yoyokirby** [comment]
没有问题了。感谢修复。
