### ISSUE TITLE
[Feature request] iOS客户端希望增加显示作品总时长的功能

### ISSUE THREAD

**Issue by rakkasumi** [Number178/kikoeru-express#22]
效果参考[asmr.one](https://asmr.one)
![image](https://github.com/Number178/kikoeru-express/assets/25529970/4994fee3-e221-4179-a836-912be5fa86aa)
 
如果网页端也有当然是极好的

**Comment by Number178** [comment]
功能已增加，testflight可以拉取最新版本app查看，注意服务器也要更新到最新版本
