### ISSUE TITLE
[Feature request] 希望加入标记ai字幕功能，手动选择文件夹内字幕文件功能，以及部分优化建议

### ISSUE THREAD

**Issue by xiaoerdedou** [Number178/kikoeru-express#35]
如题，前几天换了个模型跑模型弄出来的字幕文件放回音声文件夹内了，被识别为本地字幕，希望能做出标记ai字幕功能。
通过kikoeru-translate对无se音声跑出得到字幕不对同一音声文件夹另一子文件夹中的有se音声生效，初步推测为文件名原因，希望增加手动选择字幕文件功能。
如果以上功能得到实现，希望能在kikoeru-translate项目中加入将ai翻译放回源音声文件夹并匹配相应音声文件名的功能。

**Comment by Number178** [comment]
字幕文件放回文件系统的话，就不方便区分ai字幕了，这个暂不支持。
歌词选择、ai翻译放回文件功能已支持，可以先播放对应音频文件，等歌词加载后之后，点歌词保存，把当前正在播放的歌词保存到文件夹里。
