### ISSUE TITLE
[Bug] 无法抓取中文翻译作品封面

### ISSUE THREAD

**Issue by rakkasumi** [Number178/kikoeru-express#4]
**问题描述**

无法抓取中文翻译作品封面，元数据抓取正常

**错误信息**

**版本**

 - 系统：Linux
 - 安装方式：Docker
 - 浏览器：Chrome
 - 程序版本：20240120

**截图**

![image](https://github.com/Number178/kikoeru-express/assets/25529970/3b377997-9b5d-4fa5-b25b-7041991c2ecb)

---
**补充**
好像只有个别抓不到封面。比如RJ434125可以，但是RJ1053742就不行

**Comment by Number178** [comment]
问题已修复，这个是7位番号，导致后面的一系列bug，理论上是文件名有问题，不过这个bug也和最近支持的BJ、VJ有关系，可能老版本kikoeru是能正常抓取的，还是适配一下，修复更新已推送到dockerhub中
