### ISSUE TITLE
[Bug]  win端在扫描本地音声时, 频繁出现错误报告：Knex: Timeout acquiring a connection.

### ISSUE THREAD

**Issue by 300git** [Number178/kikoeru-express#41]
**问题描述**
在扫描本地音声时, 频繁出现如下错误报告：`Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?`

出现的原因怀疑是因为音声库太大。 
之前只有1000多音声的时候，扫描没问题
最近更新到了8000个音声档，再扫描就出现了这个问题

- 尝试更换过浏览器（vivaldi，chrome，firefox）
- 尝试清除浏览器cookie，缓存，网站设置，等等
- 尝试删了本地的数据和数据库，重新扫描
- 尝试重新下载最新的release版本

依然会出现这个问题

**错误信息**

> 共找到 8016 个音声文件夹.
> 在并行处理音声文件夹过程中出错: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

**版本**

 - 系统：Windows11专业版 23H2 22631.4169
 - 安装方式：Windows打包版
 - 浏览器：Chrome128
 - 程序版本：win-x64-v0.6.13-20240917
**截图**

![image](https://github.com/user-attachments/assets/fea4048b-aa7b-4f5f-8ca6-27bdf3adb1b4)

**Comment by 300git** [comment]
更新错误图示
![image](https://github.com/user-attachments/assets/078f945a-fcf5-4355-a59b-5b2f24f55c10)

**Comment by 300git** [comment]
测试在使用docker版的时候,
扫描8000个音声档, 使用正常, 扫描入库的速度也爆杀win打包版
而win打包版，每次扫描都会报此错误

是否是node的问题?

**Comment by Number178** [comment]
不太清楚啊，这边win上是扫描没这个问题，可能和机器、系统版本也有关系？
报错后，是一个作品都没有扫进去吗？还是扫了几个进去，但是后面作品多了就不行了？
你能试一下减少作品数量，看扫描能成功吗，单独弄一个库，放十几个带RJ的空文件夹扫着试试。

**Comment by 300git** [comment]
全清空，然后测试了十几个作品， 还是报错
然后我去搜索了一下， 尝试了一些方法， 还是解决不了
我换了笔记本电脑测试， 笔记本没问题
只能是那台PC的问题
然后我重装了系统（win11 24H2）， 重新扫描。 把8000个作品都扫描入库完了， 也没出现问题， 问题解决了

怀疑可能是那台PC曾经安装了一些莫名其妙的运行库、驱动等 哈哈
