### ISSUE TITLE
[Bug] iOS/iPad OS在后台或熄屏播放时无法自动连播

### ISSUE THREAD

**Issue by rakkasumi** [Number178/kikoeru-express#5]
**问题描述**

iOS/iPad OS在后台或熄屏播放时无法自动连播，前台播放时无异常

**错误信息**

**版本**

 - 系统：iOS 17.3.1 / iPad OS 17.3.1
 - 安装方式：Docker
 - 浏览器：Safari
 - 程序版本：20240221的镜像

**截图**

**Comment by rakkasumi** [comment]
iOS17.4之后前台也没法连播了。上一段播放完毕之后会卡住，必须点一下暂停再点一下播放才能继续，iOS端的chrome也有同样的问题

**Comment by Number178** [comment]
iOS的safari bug让人头秃，iOS的chrome基本也是用的webkit safari那套，应该是一样的问题，网页端的不太好修，关键修完说不定系统一更新就又出问题了ORZ。
目前不打算在iOS的safari里修复这些问题，所以在写iOS的native客户端，有基本播放功能，只是还得等testflight审核，审核的速度慢如龟速...

**Comment by rakkasumi** [comment]
> iOS的safari bug让人头秃，iOS的chrome基本也是用的webkit safari那套，应该是一样的问题，网页端的不太好修，关键修完说不定系统一更新就又出问题了ORZ。 目前不打算在iOS的safari里修复这些问题，所以在写iOS的native客户端，有基本播放功能，只是还得等testflight审核，审核的速度慢如龟速...

是，我都快被这玩意儿搞崩溃了。我前两天还搜到了[您的网站](https://number17.online/docs/kikoeru-app-support/)，iOS native客户端有计划开源吗？

**Comment by Number178** [comment]
啊？你怎么找到这个网站的😨
iOS native 客户端暂无开源的计划

**Comment by rakkasumi** [comment]
> 啊？你怎么找到这个网站的😨 iOS native 客户端暂无开源的计划

那就只有静候佳音了。网站谷歌上能搜到🤣

**Comment by Number178** [comment]
iOS客户端已经可以通过testflight使用，欢迎提供反馈意见，testflight链接在这里面：[KikoeruApp](https://number17.online/docs/kikoeru-app)

**Comment by rakkasumi** [comment]
> iOS客户端已经可以通过testflight使用，欢迎提供反馈意见，testflight链接在这里面：[KikoeruApp](https://number17.online/docs/kikoeru-app)

太棒了，至少连播问题解决了，感谢

**Comment by vscodev** [comment]
这不是Safari的bug，苹果就是这样规定的，见开发文档：https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html

> In Safari on iOS (for all devices, including iPad), where the user may be on a cellular network and be charged per data unit, preload and autoplay are disabled. No data is loaded until the user initiates it. This means the JavaScript play() and load() methods are also inactive until the user initiates playback, unless the play() or load() method is triggered by user action. In other words, a user-initiated Play button works, but an onLoad="play()" event does not.

**Comment by rakkasumi** [comment]
> 这不是Safari的bug，苹果就是这样规定的，见开发文档：https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/Device-SpecificConsiderations/Device-SpecificConsiderations.html
> 
> > In Safari on iOS (for all devices, including iPad), where the user may be on a cellular network and be charged per data unit, preload and autoplay are disabled. No data is loaded until the user initiates it. This means the JavaScript play() and load() methods are also inactive until the user initiates playback, unless the play() or load() method is triggered by user action. In other words, a user-initiated Play button works, but an onLoad="play()" event does not.

我没理解错的话，这段话描述的情况只涉及蜂窝网络和计费网络？但是我连接WiFi使用同样会有这个问题

**Comment by vscodev** [comment]
它这段话的意思是，在iOS的Safari中，用户可能处于特定的网络环境，所以非用户主动触发的自动播放是不被允许的，而非你理解的处于特定网络环境下的Safari。

**Comment by rakkasumi** [comment]
> 它这段话的意思是，在iOS的Safari中，用户可能处于特定的网络环境，所以非用户主动触发的自动播放是不被允许的，而非你理解的处于特定网络环境下的Safari。

 了解了，感谢

**Comment by vscodev** [comment]
我自己维护了Kikoeru的 [一个版本](https://github.com/vscodev/kikoeru) ，但我并没有升级IOS17，如果你有时间测试的话我可以单独给你编译一个用户手动触发播放的软件包用于验证。

**Comment by rakkasumi** [comment]
> 我自己维护了Kikoeru的 [一个版本](https://github.com/vscodev/kikoeru) ，但我并没有升级IOS17，如果你有时间测试的话我可以单独给你编译一个用户手动触发播放的软件包用于验证。

可以的， 已在那边仓库新开issue单独跟进

**Comment by rakkasumi** [comment]
https://github.com/vscodev/kikoeru/issues/2#issuecomment-1986314295
