### ISSUE TITLE
[Bug] 已下架音声和部分6位rj号无法爬取元数据

### ISSUE THREAD

**Issue by kohakunomiyuka** [Number178/kikoeru-express#6]
**问题描述**
已下架音声和部分6位rj号无法爬取元数据

**错误信息**

//已下架音声无法爬取
➜ 发现新文件夹: "D:\kikoeru\number17\exe版本\media\RJ01124289"
➜ 作品中是否有字幕：false
➜ 扫描音频文件时长
➜ 从 DLSite 抓取元数据...
➜ DLSite获取元数据失败: Cannot read property 'dl_count' of undefined
➜ AsmrOne获取元数据失败: connect ECONNREFUSED 127.0.0.1:80
➜ DLSite json api获取元数据失败: Cannot read property 'dl_count' of undefined
➜ 所有尝试获取元数据的方法均失败，无法添加该作品
➜ 元数据获取失败
➜ 添加失败! Failed: 1

//部分6位rj无法爬取
➜ 发现新文件夹: "D:\kikoeru\number17\exe版本\media\RJ335095"
➜ 作品中是否有字幕：false
➜ 扫描音频文件时长
➜ 从 DLSite 抓取元数据...
➜ DLSite获取元数据失败: Couldn't parse data from DLsite work page.
➜ AsmrOne获取元数据失败: connect ECONNREFUSED 127.0.0.1:80
➜ DLSite json api获取元数据失败: Couldn't parse data from DLsite work page.
➜ 所有尝试获取元数据的方法均失败，无法添加该作品
➜ 元数据获取失败
➜ 添加失败! Failed: 1
-->

**版本**

 - 系统：Windows
 - 安装方式：Windows打包版
 - 浏览器：Edge
 - 程序版本：win-x64-v0.6.7-20240221

**截图**
![99WHXYJNCOADW$NBP72NF2N](https://github.com/Number178/kikoeru-express/assets/79520731/543fa264-8f4f-476e-a07d-515b20805ebd)

![{1CXM6D2W{}CCC8D}OSLS N](https://github.com/Number178/kikoeru-express/assets/79520731/74cb1a10-440b-4ae8-8983-6e9ad342b3b2)

**Comment by Number178** [comment]
这两个作品无法导入的问题已修复，可以去release页面下载新包试试

**Comment by kohakunomiyuka** [comment]
感谢 那个rj6位的已修复 但是已下架作品似乎还是不能够全部被扫描出来
（之前有几个简中社团下架了不少作品 已修复了一个但是该社团下架的其他作品还是无法被扫描）
例如社团RG01001033和RG01007633 这两个社团下架了之后大概有好几十个简中作品直接扫描不出来了orz
![image](https://github.com/Number178/kikoeru-express/assets/79520731/98ec3aa1-f8d3-4b44-9789-9f7a7fc696c3)

**Comment by Number178** [comment]
这个下架中文作品应该只是封面下载失败，元数据还是插入成功了。修复了一下，封面从原始作品下载，可以去release更新试试
