### ISSUE TITLE
[Feature request] 性能提升

### ISSUE THREAD

**Issue by maikirakiwi** [Number178/kikoeru-express#8]
RT，[项目地址](https://github.com/WiseLibs/better-sqlite3)
在我的kikoeru实例里有完整的asmr.one库的大小（28k作品+)，当数据库里有这么多东西的时候就需要更换一个效率更高的sqlite库。

**Comment by maikirakiwi** [comment]
还有Docker其实可以把node14-alpine换成node:20-alpine
至少我自己测试编译并部署之后没有遇到任何问题。

**Comment by Number178** [comment]
better-sqlite3功能已支持，需要手动配置config.json以开启功能，怕有问题先不全量放开了，可以去dockerhub或者release页看具体配置方法。
因为windows pkg目前只支持到node18，所以docker也统一只升级到node18了。
